name: lekiwi_teleop_flutter
description: "A Flutter robot teleoperation app for LeKiwi mobile manipulator."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # Networking - App connects to bridge as WS client
  web_socket_channel: ^3.0.1

  # Hardware
  sensors_plus: ^6.1.1
  wakelock_plus: ^1.2.8
  permission_handler: ^12.0.0+1

  # Storage
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true 